name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: docker compose run web python manage.py test

      - name: Lint
        run: docker compose run web flake8

  # build:
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   # Add your build and test steps here
  #   - name: Run tests
  #     run: |
  #       # Add your test commands here

    # Add any additional steps or jobs as needed